services:
  - type: web
    name: django-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn treknepal.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: treknepal.settings
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10
