# Generated by Django 5.2.2 on 2025-06-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
