# Generated by Django 5.2.2 on 2025-07-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0002_userprofile_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('police', 'Police'), ('hospital', 'Hospital'), ('teahouse', 'Teahouse / Lodge')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
