# Generated by Django 5.2.2 on 2025-07-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0003_emergencycontactpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontactpoint',
            name='type',
            field=models.CharField(choices=[('police', 'Police'), ('hospital', 'Hospital'), ('teahouse', 'Teahouse / Lodge'), ('rescue', 'Rescue')], max_length=20),
        ),
    ]
