# Generated by Django 5.2.2 on 2025-07-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0004_alter_emergencycontactpoint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontactpoint',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontactpoint',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
