# Generated by Django 5.2.2 on 2025-07-10 03:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0005_alter_emergencycontactpoint_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('selected_types', models.JSONField()),
                ('contacted_services', models.JSONField(default=list)),
                ('google_places_data', models.JSONField(default=list)),
                ('fallback_contacts', models.JSONField(default=list)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treks.userprofile')),
            ],
        ),
    ]
