# Generated by Django 5.2.2 on 2025-07-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0006_sosalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='emergency_type',
            field=models.CharField(choices=[('health_issues', 'Health Issues'), ('lost', 'Lost'), ('theft', 'Theft'), ('rescue', 'Rescue')], default='health_issues', max_length=20),
        ),
    ]
