# Generated by Django 5.2.2 on 2025-07-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0007_sosalert_description_sosalert_emergency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timsapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
