# Generated by Django 5.2.2 on 2025-07-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0008_alter_timsapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timsapplication',
            name='transit_pass_cost',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
