# Generated by Django 5.2.2 on 2025-07-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0009_timsapplication_transit_pass_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='timsapplication',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
