# Generated by Django 5.2.2 on 2025-07-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0010_timsapplication_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timsapplication',
            options={'ordering': ['-created_at']},
        ),
    ]
