# Generated by Django 5.2.2 on 2025-07-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0011_alter_timsapplication_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='timsapplication',
            name='encrypted_qr_code',
            field=models.URLField(blank=True, null=True),
        ),
    ]
