# Generated by Django 5.2.2 on 2025-07-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0012_timsapplication_encrypted_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timsapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='home_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='home_city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='home_contact_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='home_mobile',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='home_office_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='nationality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='nepal_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='nepal_contact_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='nepal_designation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='nepal_mobile',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='nepal_office_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='nepal_organization',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='passport_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='route',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='tims_card_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='transaction_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='trekker_area',
            field=models.CharField(default='', max_length=200),
        ),
    ]
