# Generated by Django 5.2.2 on 2025-07-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0013_alter_timsapplication_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timsapplication',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='home_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='home_city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='home_contact_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='home_mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='home_office_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='nationality',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='nepal_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='nepal_contact_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='nepal_designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='nepal_mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='nepal_office_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='nepal_organization',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='passport_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='route',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='transaction_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='transit_pass_cost',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='timsapplication',
            name='trekker_area',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='TransitPass',
        ),
    ]
