# Generated by Django 5.2.2 on 2025-07-23 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0014_alter_timsapplication_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timsapplication',
            name='trek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='treks.trek'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('admin', 'Admin/Officer'), ('superadmin', 'Super Admin')], default='user', max_length=20),
        ),
    ]
