# Generated by Django 5.2.2 on 2025-07-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0017_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
