# Generated by Django 5.2.2 on 2025-11-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0018_passwordresetotp_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosalert',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('inprogress', 'In Progress'), ('resolved', 'Resolved')], default='sent', max_length=20),
        ),
    ]
