# Generated by Django 5.2.2 on 2025-11-06 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0019_alter_sosalert_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sosalert',
            options={'ordering': ['-created_at'], 'verbose_name': 'SOS Alert', 'verbose_name_plural': 'SOS Alerts'},
        ),
        migrations.AddField(
            model_name='sosalert',
            name='flagged_for_review',
            field=models.BooleanField(default=False, help_text='Needs admin review'),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='is_valid',
            field=models.BooleanField(default=True, help_text='Whether SOS is legitimate'),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sos_alerts', to='treks.userprofile'),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='validation_confidence',
            field=models.FloatField(default=1.0, help_text='AI confidence score 0-1'),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='validation_method',
            field=models.CharField(blank=True, help_text='gemini_ai, pre_check, manual', max_length=50),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='validation_reason',
            field=models.TextField(blank=True, help_text='Why flagged/approved'),
        ),
        migrations.AlterModelTable(
            name='sosalert',
            table='sos_alerts',
        ),
    ]
