# Generated by Django 5.2.2 on 2025-11-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0020_alter_sosalert_options_sosalert_flagged_for_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flagged_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_appropriate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_reason',
            field=models.TextField(blank=True),
        ),
    ]
